error messaging now uses error.
setting progname to `licensing COMMAND' when not calling from lush shell.

diff --git a/src/preview.in b/src/preview.in
--- a/src/preview.in
+++ b/src/preview.in
@@ -1,4 +1,4 @@
-#!/usr/bin/env @INTERPRETER@
+#!/usr/bin/env bash
 # Copyright (C) 2013 Ben Asselstine
 # 
 # This program is free software: you can redistribute it and/or modify
@@ -14,15 +14,20 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+if [[ "$BASH_ENV" == *\.lushrc* ]]; then
+  progname=$(basename $0)
+else
+  progname="licensing $(basename $0)"
+fi
 showusage() {
   cat <<EOF
-Usage: $(basename $0) [-?] [--no-commenting-style] [--help] [--usage]
+Usage: ${progname} [-?] [--no-commenting-style] [--help] [--usage]
 EOF
 }
 
 showhelp() {
   cat <<EOF
-Usage: $(basename $0) [OPTION...]
+Usage: ${progname} [OPTION...]
 Show the current working boilerplate.
 
       --no-commenting-style  show the boilerplate without comment delimiters
@@ -44,25 +49,25 @@ do
     nostyle=1
     shift;;
   --*)
-    echo >&2 "$(basename $0): $option: unknown option"
+    echo >&2 "${progname}: $option: unknown option"
     exit 1;;
   esac
 done
 
 if [[ $# -ge 1 ]]; then
-  echo "$(basename $0): Too many arguments"
-  echo "Try '$(basename $0) --help' or '$(basename $0) --usage' for more information."
+  echo "${progname}: Too many arguments"
+  echo "Try '${progname} --help' or '${progname}--usage' for more information."
   exit 1
 fi
 
 if [[ ! -f ~/.@PACKAGE@/license-notice ]]; then
-  echo "$(basename $0): Can't preview because a license has not been selected"
+  echo "${progname}: Can't preview because a license has not been selected"
   echo "Try 'choose --help' for more information."
   exit 1
 fi
 
 if [[ ! -f ~/.@PACKAGE@/copyright-holders ]]; then
-  echo "$(basename $0): Can't preview because copyright holders not been specified"
+  echo "${progname}: Can't preview because copyright holders not been specified"
   echo "Try 'copyright --help' for more information."
   exit 1
 fi
